"""create_document_tables

Revision ID: 13f0a3c7c1ae
Revises: 25801f3082fa
Create Date: 2026-05-21 07:10:54.083929

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '13f0a3c7c1ae'
down_revision: Union[str, None] = '25801f3082fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('offer_letter', 'appointment_letter', 'experience_letter', 'relieving_letter', 'salary_certificate', 'form_16', 'custom', name='documenttype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_html', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('offer_letter', 'appointment_letter', 'experience_letter', 'relieving_letter', 'salary_certificate', 'form_16', 'custom', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'generated', 'issued', name='documentstatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
