"""add_employee_role_and_user_employee_link

Revision ID: 25801f3082fa
Revises: aa88e7137263
Create Date: 2026-05-21 06:55:18.966149

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '25801f3082fa'
down_revision: Union[str, None] = 'aa88e7137263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
