"""initial

Revision ID: aa88e7137263
Revises: 
Create Date: 2026-05-18 09:20:46.306455

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'aa88e7137263'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('payslip_footer_text', sa.Text(), nullable=True),
    sa.Column('watermark_opacity', sa.Float(), nullable=False),
    sa.Column('working_days_per_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('uan', sa.String(length=20), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'on_notice', 'archived', name='employeestatus'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('default_days_per_year', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('is_carry_forward', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'hr_admin', 'hr_staff', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'half_day', 'work_from_home', 'on_leave', 'holiday', 'week_off', name='attendancestatus'), nullable=False),
    sa.Column('check_in', sa.String(length=10), nullable=True),
    sa.Column('check_out', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_date')
    )
    op.create_table('leave_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('remaining_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_emp_leave_year')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type_id', sa.String(length=36), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('num_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leaverequeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processed', 'locked', name='payrollstatus'), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('processed_by', sa.String(length=36), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.Column('percentage_of', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslip_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payroll_run_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('days_absent', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('leaves_taken', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('earnings_breakdown', sa.JSON(), nullable=False),
    sa.Column('deductions_breakdown', sa.JSON(), nullable=False),
    sa.Column('ytd_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ytd_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('is_pdf_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslip_records')
    op.drop_table('salary_components')
    op.drop_table('payroll_runs')
    op.drop_table('leave_requests')
    op.drop_table('leave_balances')
    op.drop_table('attendance_records')
    op.drop_table('users')
    op.drop_table('leave_types')
    op.drop_table('employees')
    op.drop_table('organizations')
    # ### end Alembic commands ###
